[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]
live_config_reload = true

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[window]
opacity = 1

# Colors Modus-Vivendi-Tinted
[colors.normal]
black = '#1d2235'
red = '#ff5f59'
green = '#44bc44'
yellow = '#d0bc00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#ffffff'
[colors.bright]
black = '#4a4f69'
red = '#ff7f9f'
green = '#00c06f'
yellow = '#dfaf7a'
blue = '#00bcff'
magenta = '#b6a0ff'
cyan = '#6ae4b9'
white = '#989898'
[colors.cursor]
cursor = '#ffffff'
text = '#0d0e1c'
[colors.primary]
background = '#0d0e1c'
foreground = '#ffffff'
[colors.selection]
background = '#555a66'
text = '#ffffff'
